version: "3.8"

name: api-doc-conf
services:
  swagger-ui:
    container_name: swagger-multiple-services
    build:
      context: .
    volumes:
      - ./api-doc:/usr/share/nginx/html/api-doc:rw
      - ./swagger-initializer.js:/usr/share/nginx/html/swagger-initializer.js
    ports:
      - "8092:8090"
    networks:
      - api-doc-conf

networks:
  api-doc-conf:
