version: "3.8"

name: api-doc-conf
services:
  swagger-ui:
    container_name: api-doc-service
    build:
      context: .
    volumes:
      - ./api-doc:/usr/share/nginx/html/api-doc:rw
      - ./settings.js:/usr/share/nginx/html/settings.js
    ports:
      - "8093:8090"
    networks:
      - api-doc-conf

networks:
  api-doc-conf:
